language: node_js
node_js:
  - "node"
cache:
  directories:
    - node_modules
script: npm run test:compat && npm run test:hook
after_success:
  - bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION
